import type { Evidence, EvidenceType, Investigation } from "./types";

/**
 * 100% FICTIONAL / SYNTHETIC DEMO DATA.
 * No real persons, vehicles, cameras, phone records or police data.
 */

let counter = 1000;
export const nextId = (prefix: string) => `${prefix}-${++counter}`;

const ev = (
  caseId: string,
  seq: number,
  type: EvidenceType,
  label: string,
  source: string,
  timestamp: string,
  locationName: string,
  lat: number,
  lng: number,
  reliability: number,
  details: string,
  interpretation: string,
  keywords: string[],
): Evidence => ({
  id: `${caseId}-E${String(seq).padStart(2, "0")}`,
  caseId,
  type,
  label,
  source,
  timestamp,
  locationName,
  lat,
  lng,
  reliability,
  details,
  interpretation,
  keywords,
  stage: "CORRELATED",
});

export const CHENNAI_BOUNDS = {
  minLat: 12.78,
  maxLat: 13.29,
  minLng: 79.98,
  maxLng: 80.42,
};

export const LOCATION_PRESETS: { name: string; lat: number; lng: number }[] = [
  { name: "T. Nagar, Chennai", lat: 13.0418, lng: 80.2341 },
  { name: "Egmore Station, Chennai", lat: 13.0785, lng: 80.2609 },
  { name: "Koyambedu Bus Terminus", lat: 13.0694, lng: 80.1948 },
  { name: "Marina Beach Road", lat: 13.0555, lng: 80.2825 },
  { name: "Guindy Industrial Estate", lat: 12.9942, lng: 80.2116 },
  { name: "Tambaram Sanatorium", lat: 12.9249, lng: 80.1229 },
  { name: "Velachery Bypass", lat: 12.9791, lng: 80.2211 },
  { name: "Anna Nagar West", lat: 13.0878, lng: 80.2015 },
  { name: "Chengalpattu Town", lat: 12.6819, lng: 79.9864 },
  { name: "Avadi Check Post", lat: 13.1147, lng: 80.1098 },
  { name: "Perungudi Toll Plaza", lat: 12.9639, lng: 80.2452 },
  { name: "Kanchipuram Outskirts", lat: 12.8342, lng: 79.7036 },
  { name: "Ambattur Estate", lat: 13.1143, lng: 80.1548 },
  { name: "Mylapore Tank Road", lat: 13.0339, lng: 80.2686 },
];

function buildSeed(): Investigation[] {
  const c1 = "CL-2481";
  const c2 = "CL-2492";
  const c3 = "CL-2503";
  const c4 = "CL-2514";
  const c5 = "CL-2525";
  const c6 = "CL-2536";

  return [
    {
      id: c1,
      code: c1,
      title: "Disappearance of Meera Ravikumar",
      type: "Missing Person",
      priority: "Critical",
      status: "Active",
      subject: {
        name: "Meera Ravikumar",
        aliases: ["Meera R.", "Meeru"],
        age: 19,
        phone: "+91 90000 41287",
        vehicle: "TN-09-BX-4471 (white hatchback)",
        description:
          "College student, last seen wearing a dark green kurta and carrying a grey backpack.",
      },
      incidentDate: "2026-08-09T18:40:00.000Z",
      lastKnownLocation: "T. Nagar, Chennai",
      district: "Chennai South",
      notes:
        "Subject left tuition centre at Ranganathan Street and did not reach home. Family reports an unfamiliar white hatchback seen twice near residence during the week.",
      modusOperandi: "Vehicle-assisted approach near crowded market street",
      witnesses: ["Suresh Anand", "Kalpana Devi"],
      officer: "Insp. A. Vetrivel",
      createdAt: "2026-08-09T21:10:00.000Z",
      evidence: [
        ev(
          c1,
          1,
          "CCTV",
          "Camera CAM-TN-114 — market exit",
          "Synthetic CCTV grid CAM-TN-114",
          "2026-08-09T18:44:00.000Z",
          "T. Nagar, Chennai",
          13.0418,
          80.2341,
          88,
          "Subject exits south gate alone, pauses, then moves east along the service lane.",
          "Departure direction east contradicts habitual route home (north), suggesting an unplanned deviation.",
          ["white hatchback", "grey backpack", "market exit"],
        ),
        ev(
          c1,
          2,
          "Witness",
          "Statement — Suresh Anand (tea stall)",
          "Witness statement WS-118",
          "2026-08-09T18:52:00.000Z",
          "Mylapore Tank Road",
          13.0339,
          80.2686,
          64,
          "Witness recalls a young woman matching description speaking with a man near a white hatchback.",
          "Moderate reliability: recollection of vehicle colour is consistent across two independent statements.",
          ["white hatchback", "TN-09-BX-4471", "male companion"],
        ),
        ev(
          c1,
          3,
          "Phone",
          "Handset last activity ping",
          "Synthetic telecom ping set P-4471",
          "2026-08-09T19:26:00.000Z",
          "Perungudi Toll Plaza",
          12.9639,
          80.2452,
          79,
          "Final network activity recorded south-west of last visual sighting, then device silent.",
          "Movement vector implies southbound travel along the arterial corridor at vehicle speed.",
          ["+91 90000 41287", "southbound", "device silent"],
        ),
        ev(
          c1,
          4,
          "Transport",
          "Toll gantry read — TN-09-BX-4471",
          "Synthetic transport log T-771",
          "2026-08-09T19:31:00.000Z",
          "Perungudi Toll Plaza",
          12.9639,
          80.2452,
          91,
          "White hatchback bearing plate TN-09-BX-4471 recorded crossing southbound.",
          "Strong corroboration: vehicle read occurs 5 minutes after the final handset ping in the same cell.",
          ["TN-09-BX-4471", "southbound", "toll gantry"],
        ),
        ev(
          c1,
          5,
          "Location",
          "Search sweep — Chengalpattu corridor",
          "Field team log F-22",
          "2026-08-10T06:15:00.000Z",
          "Chengalpattu Town",
          12.6819,
          79.9864,
          55,
          "Ground team recovered a grey backpack strap near the bypass shoulder.",
          "Low-moderate confidence article match; forensic confirmation pending human review.",
          ["grey backpack", "bypass", "recovered article"],
        ),
      ],
    },
    {
      id: c2,
      code: c2,
      title: "Residential Burglary — Anna Nagar West",
      type: "Burglary",
      priority: "High",
      status: "Active",
      subject: {
        name: "Unidentified suspect (Suspect A)",
        aliases: ["Kannan", "Kannan Anna"],
        phone: "+91 90000 41287",
        vehicle: "TN-09-BX-4471 (white hatchback)",
        description: "Male, medium build, dark cap, canvas shoulder bag.",
      },
      incidentDate: "2026-08-07T02:10:00.000Z",
      lastKnownLocation: "Anna Nagar West",
      district: "Chennai West",
      notes:
        "Entry through rear utility window, jewellery and cash removed. Neighbour photographed a white hatchback idling in the lane. Same handset number appears in an unrelated complaint.",
      modusOperandi: "Rear window entry, night hours, lookout vehicle idling",
      weapon: "Pry bar (suspected)",
      witnesses: ["Kalpana Devi"],
      officer: "SI R. Manimekalai",
      createdAt: "2026-08-07T05:40:00.000Z",
      evidence: [
        ev(
          c2,
          1,
          "CCTV",
          "Camera CAM-AN-207 — lane approach",
          "Synthetic CCTV grid CAM-AN-207",
          "2026-08-07T01:58:00.000Z",
          "Anna Nagar West",
          13.0878,
          80.2015,
          83,
          "Two figures approach on foot; a white hatchback reverses into the lane and waits.",
          "Vehicle behaviour is consistent with a lookout pattern rather than a resident parking.",
          ["white hatchback", "lookout", "night entry"],
        ),
        ev(
          c2,
          2,
          "Photo",
          "Neighbour photograph — plate partial",
          "Civilian photo PH-91",
          "2026-08-07T02:04:00.000Z",
          "Anna Nagar West",
          13.0878,
          80.2015,
          72,
          "Partial plate legible as TN-09-BX-44** on a white hatchback.",
          "Partial plate is a strong lead: only one synthetic record in the corpus matches the pattern.",
          ["TN-09-BX-4471", "partial plate", "white hatchback"],
        ),
        ev(
          c2,
          3,
          "Witness",
          "Statement — Kalpana Devi",
          "Witness statement WS-092",
          "2026-08-07T08:20:00.000Z",
          "Anna Nagar West",
          13.0878,
          80.2015,
          68,
          "Witness heard a man addressed as 'Kannan' and describes a canvas shoulder bag.",
          "Alias 'Kannan' recurs in two other open files, raising cross-case relevance.",
          ["Kannan", "canvas bag", "alias"],
        ),
        ev(
          c2,
          4,
          "Phone",
          "Handset cluster activity",
          "Synthetic telecom ping set P-4471",
          "2026-08-07T02:22:00.000Z",
          "Ambattur Estate",
          13.1143,
          80.1548,
          77,
          "Handset +91 90000 41287 active in adjacent cell minutes after the entry window.",
          "Same handset identifier as the missing-person file — a high-weight cross-case attribute.",
          ["+91 90000 41287", "adjacent cell"],
        ),
      ],
    },
    {
      id: c3,
      code: c3,
      title: "Chain Snatching — Velachery Bypass",
      type: "Theft",
      priority: "Medium",
      status: "Active",
      subject: {
        name: "Unidentified suspect (Suspect B)",
        aliases: ["Kannan"],
        vehicle: "TN-11-AC-9032 (black motorcycle)",
        description: "Two riders, pillion rider snatched chain and fled south.",
      },
      incidentDate: "2026-08-08T20:05:00.000Z",
      lastKnownLocation: "Velachery Bypass",
      district: "Chennai South",
      notes:
        "Snatch executed at signal halt. Riders headed toward Perungudi. Complainant recalls the pillion rider being called 'Kannan'.",
      modusOperandi: "Two-rider snatch at signal halt, southbound escape",
      witnesses: ["Suresh Anand"],
      officer: "SI R. Manimekalai",
      createdAt: "2026-08-08T21:30:00.000Z",
      evidence: [
        ev(
          c3,
          1,
          "CCTV",
          "Camera CAM-VL-058 — signal junction",
          "Synthetic CCTV grid CAM-VL-058",
          "2026-08-08T20:06:00.000Z",
          "Velachery Bypass",
          12.9791,
          80.2211,
          80,
          "Motorcycle halts beside complainant, pillion reaches out, vehicle accelerates south.",
          "Escape vector matches the arterial corridor used in two other open files.",
          ["black motorcycle", "TN-11-AC-9032", "southbound"],
        ),
        ev(
          c3,
          2,
          "Transport",
          "Corridor camera read — motorcycle",
          "Synthetic transport log T-802",
          "2026-08-08T20:19:00.000Z",
          "Perungudi Toll Plaza",
          12.9639,
          80.2452,
          74,
          "Motorcycle TN-11-AC-9032 recorded on the southbound service road.",
          "Geographic overlap with the missing-person corridor within a 24-hour window.",
          ["TN-11-AC-9032", "service road"],
        ),
        ev(
          c3,
          3,
          "Witness",
          "Statement — Suresh Anand",
          "Witness statement WS-118",
          "2026-08-08T20:40:00.000Z",
          "Velachery Bypass",
          12.9791,
          80.2211,
          61,
          "Same witness as the T. Nagar file; recalls the name 'Kannan' shouted by the rider.",
          "Shared witness across two files is a strong structural link, independent of forensic evidence.",
          ["Kannan", "shared witness"],
        ),
      ],
    },
    {
      id: c4,
      code: c4,
      title: "Assault Outside Koyambedu Terminus",
      type: "Assault",
      priority: "High",
      status: "Under Review",
      subject: {
        name: "Unidentified suspect (Suspect C)",
        aliases: ["Kannan Anna"],
        vehicle: "TN-09-BX-4471 (white hatchback)",
        description: "Male, dark cap, fled in a white hatchback with a second man.",
      },
      incidentDate: "2026-08-06T22:48:00.000Z",
      lastKnownLocation: "Koyambedu Bus Terminus",
      district: "Chennai West",
      notes:
        "Victim assaulted while resisting a bag snatch near platform 6. Pry bar recovered from the scene.",
      modusOperandi: "Bag snatch escalating to assault, vehicle escape",
      weapon: "Pry bar",
      witnesses: ["Ilango Selvam"],
      officer: "Insp. A. Vetrivel",
      createdAt: "2026-08-06T23:55:00.000Z",
      evidence: [
        ev(
          c4,
          1,
          "CCTV",
          "Camera CAM-KY-311 — platform 6",
          "Synthetic CCTV grid CAM-KY-311",
          "2026-08-06T22:49:00.000Z",
          "Koyambedu Bus Terminus",
          13.0694,
          80.1948,
          86,
          "Struggle recorded; two men leave the frame toward the west gate parking bay.",
          "Timing and clothing description align with the Anna Nagar burglary suspect pair.",
          ["dark cap", "two men", "west gate"],
        ),
        ev(
          c4,
          2,
          "Photo",
          "Scene photograph — recovered pry bar",
          "Scene photo PH-140",
          "2026-08-06T23:30:00.000Z",
          "Koyambedu Bus Terminus",
          13.0694,
          80.1948,
          90,
          "Pry bar recovered near the parking bay, tool marks documented.",
          "Weapon type matches the suspected entry tool in the burglary file.",
          ["pry bar", "tool marks", "weapon"],
        ),
        ev(
          c4,
          3,
          "Transport",
          "Parking bay read — white hatchback",
          "Synthetic transport log T-655",
          "2026-08-06T22:56:00.000Z",
          "Koyambedu Bus Terminus",
          13.0694,
          80.1948,
          81,
          "White hatchback TN-09-BX-4471 exits the terminus parking bay.",
          "Third independent appearance of the same synthetic plate across separate files.",
          ["TN-09-BX-4471", "white hatchback"],
        ),
      ],
    },
    {
      id: c5,
      code: c5,
      title: "Missing Elderly Person — Tambaram",
      type: "Missing Person",
      priority: "High",
      status: "Active",
      subject: {
        name: "Rajaraman Iyer",
        aliases: ["Raja thatha"],
        age: 74,
        phone: "+91 90000 77310",
        description:
          "Retired schoolteacher with memory impairment, last seen at the suburban platform.",
      },
      incidentDate: "2026-08-11T07:20:00.000Z",
      lastKnownLocation: "Tambaram Sanatorium",
      district: "Chennai South",
      notes:
        "Walked out for a morning errand and did not return. Vulnerable adult protocol invoked.",
      modusOperandi: "Wandering behaviour, transit corridor",
      witnesses: ["Ilango Selvam"],
      officer: "SI P. Aarthi",
      createdAt: "2026-08-11T09:05:00.000Z",
      evidence: [
        ev(
          c5,
          1,
          "CCTV",
          "Camera CAM-TB-019 — platform 1",
          "Synthetic CCTV grid CAM-TB-019",
          "2026-08-11T07:24:00.000Z",
          "Tambaram Sanatorium",
          12.9249,
          80.1229,
          84,
          "Subject boards a northbound suburban service without assistance.",
          "Boarding direction indicates travel toward the central corridor, not homeward.",
          ["northbound", "suburban service", "vulnerable adult"],
        ),
        ev(
          c5,
          2,
          "Witness",
          "Statement — Ilango Selvam",
          "Witness statement WS-203",
          "2026-08-11T08:10:00.000Z",
          "Egmore Station, Chennai",
          13.0785,
          80.2609,
          70,
          "Vendor recalls an elderly man asking directions to a school that closed years ago.",
          "Consistent with memory impairment; supports the central-corridor hypothesis.",
          ["disorientation", "school", "central corridor"],
        ),
        ev(
          c5,
          3,
          "Phone",
          "Handset ping — single activation",
          "Synthetic telecom ping set P-7731",
          "2026-08-11T09:02:00.000Z",
          "Egmore Station, Chennai",
          13.0785,
          80.2609,
          76,
          "One activation recorded in the Egmore cell before the battery drained.",
          "Corroborates the witness sighting within a 52-minute window.",
          ["+91 90000 77310", "single activation"],
        ),
      ],
    },
    {
      id: c6,
      code: c6,
      title: "Two-Wheeler Theft Cluster — Ambattur",
      type: "Vehicle Crime",
      priority: "Medium",
      status: "Active",
      subject: {
        name: "Unidentified group (Cluster D)",
        aliases: [],
        vehicle: "TN-11-AC-9032 (black motorcycle)",
        description: "Repeat thefts of parked two-wheelers in industrial lanes.",
      },
      incidentDate: "2026-08-10T23:15:00.000Z",
      lastKnownLocation: "Ambattur Estate",
      district: "Chennai West",
      notes:
        "Fourth two-wheeler taken from the same lane cluster this month. Ignition tampering consistent across incidents.",
      modusOperandi: "Ignition tampering, industrial lanes, late night",
      witnesses: [],
      officer: "SI P. Aarthi",
      createdAt: "2026-08-11T02:20:00.000Z",
      evidence: [
        ev(
          c6,
          1,
          "CCTV",
          "Camera CAM-AB-402 — lane 7",
          "Synthetic CCTV grid CAM-AB-402",
          "2026-08-10T23:16:00.000Z",
          "Ambattur Estate",
          13.1143,
          80.1548,
          78,
          "Rider arrives on a black motorcycle, departs with a second two-wheeler alongside.",
          "Escort-departure pattern implies at least two participants.",
          ["black motorcycle", "TN-11-AC-9032", "ignition tampering"],
        ),
        ev(
          c6,
          2,
          "Location",
          "Recovery point — Avadi check post",
          "Field team log F-31",
          "2026-08-11T04:40:00.000Z",
          "Avadi Check Post",
          13.1147,
          80.1098,
          69,
          "One stolen two-wheeler recovered abandoned near the check post.",
          "Recovery corridor overlaps the burglary handset cluster area.",
          ["recovery", "check post", "corridor"],
        ),
      ],
    },
  ];
}

export const SEED_CASES: Investigation[] = buildSeed();

export const CASE_TYPES = [
  "Missing Person",
  "Burglary",
  "Theft",
  "Assault",
  "Vehicle Crime",
] as const;

export const PRIORITIES = ["Critical", "High", "Medium", "Low"] as const;

export const EVIDENCE_TYPES = [
  "CCTV",
  "Witness",
  "Phone",
  "Photo",
  "Transport",
  "Location",
] as const;
